version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - jiknet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer/:/data
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    volumes:
      - /opt/nginx-proxy-manager/:/data
      - /opt/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "8081:81"
      - "443:443"
networks:
  default:
    external:
      name: jiknet